//! # Landing Page Component
//!
//! Displays an animated ASCII art sequence when the conversation is empty.
//!

use ratatui::Frame;
use ratatui::layout::Rect;
use ratatui::widgets::Paragraph;
use ratatui::widgets::canvas::{Canvas, Shape, Context};
use ratatui::style::{Style, Color};
use ratatui::layout::Alignment;
use crate::tui::component::Component;

pub struct LandingPage {
    frame_index: usize,
}

impl LandingPage {
    pub fn new(frame_index: usize) -> Self {
        Self { frame_index }
    }
}

// Embedded ASCII frames (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/landing_frames.rs"));

impl Component for LandingPage {
    fn render(&mut self, frame: &mut Frame, area: Rect) {
        let frame_count = LANDING_FRAMES.len();
        if frame_count == 0 { return; }
        
        // Slow down animation (divide by 3)
        let slow_frame_index = self.frame_index / 3;
        let current_frame_idx = slow_frame_index % frame_count;
        let points = LANDING_FRAMES[current_frame_idx];

        use ratatui::text::{Line, Span};
        use ratatui::style::Modifier;
        use ratatui::layout::{Layout, Constraint, Flex};

        // --- Prepare Text for Layout Calculation ---
        let mut text_lines = Vec::new();
        // Spacer is handled by layout splitting now
        
        text_lines.push(Line::from(Span::styled(
            "Hey! Listen!",
            Style::default().fg(Color::Yellow).add_modifier(Modifier::BOLD)
        )));

        text_lines.push(Line::from(Span::styled(
            "Navi",
            Style::default().fg(Color::DarkGray)
        )));

        let version_text = format!("v{}", env!("CARGO_PKG_VERSION"));
        text_lines.push(Line::from(Span::styled(
            version_text,
            Style::default().fg(Color::DarkGray)
        )));
        
        // --- Calculate Layout ---
        // We want the Canvas to take up natural height of the fairy
        // And the text to be below it.
        // We want the whole group centered vertically.
        
        // Canvas Height in ROWS = Dot Height / 4.
        let fairy_rows = (FAIRY_HEIGHT / 4.0).ceil() as u16;
        let canvas_height = fairy_rows + 2; // Add a bit of breathing room/padding
        
        // Canvas Width in COLS = Dot Width / 2.
        let fairy_cols = (FAIRY_WIDTH / 2.0).ceil() as u16;
        // add a bit of safety margin?
        let canvas_width = fairy_cols + 2;

        let text_height = text_lines.len() as u16;

        let vertical_layout = Layout::vertical([
            Constraint::Length(canvas_height),
            Constraint::Length(1), // Spacer
            Constraint::Length(text_height),
        ]).flex(Flex::Center)
        .split(area);
        
        // Horizontal Layout to constrain width (prevent stretching)
        let horizontal_layout = Layout::horizontal([
            Constraint::Length(canvas_width)
        ]).flex(Flex::Center)
        .split(vertical_layout[0]);
        
        // --- Render Canvas (Fairy) ---
        // We need to match the bounds precisely to the widget size to avoid scaling.
        // Widget Width (dots) = canvas_width * 2
        // Widget Height (dots) = canvas_height * 4
        // Our Data: [0, FAIRY_WIDTH], [0, FAIRY_HEIGHT]
        
        // We should center the data within the canvas bounds if there's excess space.
        // OR just set the bounds to the projected size.
        
        let canvas_max_x = (canvas_width as f64) * 2.0;
        let canvas_max_y = (canvas_height as f64) * 4.0;
        
        // We want the Center of Mass (FAIRY_COM_X) to be at the Center of the Canvas.
        // Canvas Center = canvas_max_x / 2.0.
        // Shift Needed = Target - Source.
        // Source = FAIRY_COM_X. Target = canvas_max_x / 2.0.
        // offset_x = (canvas_max_x / 2.0) - FAIRY_COM_X;
        
        // Manual Nudge: The visual center of the body seems to be about 4-5 dots to the right
        // of where it's currently rendering.
        // Positive Nudge -> Moves Fairy RIGHT.
        // Negative Nudge -> Moves Fairy LEFT.
        const MANUAL_NUDGE: f64 = -1.0; 
        
        let offset_x = (canvas_max_x / 2.0) - FAIRY_COM_X + MANUAL_NUDGE;
        let offset_y = (canvas_max_y - FAIRY_HEIGHT) / 2.0;
        
        let canvas = Canvas::default()
            .x_bounds([0.0, canvas_max_x])
            .y_bounds([0.0, canvas_max_y])
            .paint(move |ctx| {
                ctx.draw(&Dots {
                    points,
                    color: Color::Blue,
                    offset_x,
                    offset_y,
                    canvas_max_y,
                });
            });
            
        frame.render_widget(canvas, horizontal_layout[0]);

        // --- Render Text ---
        let paragraph = Paragraph::new(text_lines)
            .alignment(Alignment::Center);

        frame.render_widget(paragraph, vertical_layout[2]);
    }
}

// Helper Shape for drawing dots
struct Dots<'a> {
    points: &'a [(f64, f64)],
    color: Color,
    offset_x: f64,
    offset_y: f64,
    canvas_max_y: f64,
}

impl<'a> Shape for Dots<'a> {
    fn draw(&self, painter: &mut ratatui::widgets::canvas::Painter) {
        for (x, y) in self.points {
            let draw_x = x + self.offset_x;
            
            // Image Y=0 is TOP. Canvas Y=0 is BOTTOM.
            // We want (x, 0) to be drawn at (x, canvas_max_y - offset_y).
            // We want (x, h) to be drawn at (x, canvas_max_y - offset_y - h).
            
            let draw_y = (self.canvas_max_y - self.offset_y) - y;
            
            if let Some((rx, ry)) = painter.get_point(draw_x, draw_y) {
                 painter.paint(rx, ry, self.color);
            }
        }
    }
}
