//! # Landing Page Component
//!
//! Displays an animated ASCII art sequence when the conversation is empty.
//!

use ratatui::Frame;
use ratatui::layout::Rect;
use ratatui::widgets::Paragraph;
use ratatui::style::{Style, Color};
use ratatui::layout::Alignment;
use crate::tui::component::Component;

pub struct LandingPage {
    frame_index: usize,
}

impl LandingPage {
    pub fn new(frame_index: usize) -> Self {
        Self { frame_index }
    }
}

impl Component for LandingPage {
    fn render(&mut self, frame: &mut Frame, area: Rect) {
        let frame_count = ASCII_FRAMES.len();
        if frame_count == 0 { return; }
        
        // Slow down animation (divide by 3)
        let slow_frame_index = self.frame_index / 3;
        let current_frame_idx = slow_frame_index % frame_count;
        let text = ASCII_FRAMES[current_frame_idx];

        // Vertical Centering Logic
        let lines: Vec<&str> = text.lines().collect();
        let content_height = lines.len() as u16;
        
        // Calculate centered vertical area
        let centered_area = if area.height > content_height {
            let y_offset = (area.height - content_height) / 2;
            Rect {
                x: area.x,
                y: area.y + y_offset,
                width: area.width,
                height: content_height,
            }
        } else {
            area // If too small, just render in full area (will crop)
        };

        let paragraph = Paragraph::new(text)
            // Removed border to make it look cleaner vertically centered
            // .block(Block::bordered().border_type(BorderType::Rounded)) 
            .style(Style::default().fg(Color::Blue))
            .alignment(Alignment::Center);

        frame.render_widget(paragraph, centered_area);
    }
}

// Embedded ASCII frames (generated by build.rs)
include!(concat!(env!("OUT_DIR"), "/landing_frames.rs"));
